{
    "meta":{ "title":"Film Titles & Gaze Mechanisms — Examples" },
    "concepts":[
      // BLADE RUNNER 2049
      { "id":"br2049-k-opening", "term":"Blade Runner "2049": K\"s Opening", "sections":{
        "definition":"The film opens establishing <K> as the <active male> <protagonist>, whose <gaze> is one of detached [control] and [investigation], firmly aligning the <spectator> with his <subjectivity>. The barren <landscape> and brutal [retirement] of <Sapper Morton> [code] the <spectator> to accept <K>\"s <power> within the <patriarchal symbolic order> of this dystopian <film world>. This initial sequence sets the stage for <female figures> to become <objects> of his mission or <desire>, reinforcing the <mainstream cinema>\"s <algorithm for desire> through <narcissistic identification> with the <male hero> who [makes things happen].",
        "powerful_quote":""As the spectator identifies with the main male protagonist, he projects his look on to that of his like, his screen surrogate, so that the power of the male protagonist as he controls events coincides with the active power of the erotic look, both giving a satisfying sense of omnipotence. The character in the story can make things happen and control events better than the subject/spectator, just as the image in the mirror was more in control of motor coordination."",
        "summary":"<K>\"s introduction codes his <active controlling gaze>, positioning the <audience> with the <male protagonist> and reinforcing his <power> in the <patriarchal symbolic order>, establishing a foundation for <narcissistic identification>.",
        "key_terms":["<K>","<active male>","<protagonist>","<gaze>","[control]","[investigation]","<spectator>","<subjectivity>","<landscape>","[retirement]","<Sapper Morton>","[code]","<power>","<patriarchal symbolic order>","<film world>","<female figures>","<objects>","<desire>","<mainstream cinema>","<algorithm for desire>","<narcissistic identification>","<male hero>","[makes things happen]"],
        "media": [{"type":"youtube", "id":"hR8f5vFvX7k"}] // Blade Runner 2049 opening scene with Sapper Morton
      }},
      { "id":"br2049-joi-mariette", "term":"Blade Runner "2049": Joi & Mariette Scene", "sections":{
        "definition":"This scene exemplifies extreme <fetishistic scopophilia> as an <avenue of escape> from <castration anxiety>. <Joi>, a holographic <AI>, is the ultimate <fetish object>, a "perfect product" designed for <K>\"s <desire>. Her [superimposition] onto <Mariette>\"s <body> uses advanced <VFX> as <attention design> to [create] a seamless <erotic spectacle>. This [complete disavowal of castration] is achieved by presenting a flawless, controllable <female form> that [alleviates anxiety], ensuring <K>\"s <satisfaction> without the complexities of human <agency>. <Mariette>\"s brief, cynical <counter-gaze> at <K> ("You don\"t like real girls?") momentarily [disrupts] this illusion, but <Joi> remains the dominant <fetish>, designed to provide <reassuring pleasure> that [exists outside linear time] of organic complication.",
        "powerful_quote":""The male unconscious has two avenues of escape from this castration anxiety... or else complete disavowal of castration by the substitution of a fetish object or turning the represented figure itself into a fetish so that it becomes reassuring rather than dangerous (hence over-valuation, the cult of the female star). This second avenue, fetishistic scopophilia, builds up the physical beauty of the object, transforming it into something satisfying in itself." AND "Fetishistic scopophilia, on the other hand, can exist outside linear time as the erotic instinct is focussed on the look alone."",
        "summary":"<Joi> represents the technologically perfected <fetish>, her <physical proxy> (<Mariette>) subsumed by programmed <desire>, with a minor <counter-gaze> that briefly exposes the <artifice> but fails to break the pervasive <fetishistic scopophilia>.",
        "key_terms":["<fetishistic scopophilia>","<avenue of escape>","<castration anxiety>","<Joi>","<AI>","<fetish object>","<K>","<desire>","[superimposition]","<Mariette>","<body>","<VFX>","<attention design>","<erotic spectacle>","[complete disavowal of castration]","<female form>","[alleviates anxiety]","<satisfaction>","<agency>","<counter-gaze>","[disrupts]","<reassuring pleasure>","[exists outside linear time>","<artifice>"]
      }},
      // EX MACHINA
      { "id":"exm-caleb-opening", "term":"Ex "Machina": Caleb\"s Arrival", "sections":{
        "definition":"The opening establishes <Caleb>\"s sudden wealth and isolation, setting him up as the <spectator> within the narrative, ready for <scopophilia> as [investigation]. His <curiosity> is piqued by the <mystery> of <Nathan>\"s remote, luxurious estate. The <attention design> of the isolated, glass-encased <environment> [primes] the <audience> for <voyeurism> towards the "private and the forbidden," foreshadowing the <female figures> (<Ava> and other <AIs>) he will encounter and the subsequent [demystification] of <Ava>\"s <AI> through an <active controlling gaze>, inviting the spectator into a shared role of <scientific voyeurism>.",
        "powerful_quote":""Originally, in his Three Essays on Sexuality, Freud isolated scopophilia as one of the component instincts of sexuality which exist as drives quite independently of the erotogenic zones. At this point he associated scopophilia with taking other people as objects, subjecting them to a controlling and curious gaze. His particular examples centre around the voyeuristic activities of children, their desire to see and make sure of the private and the forbidden (curiosity about other people’s genital and bodily functions, about the presence or absence of the penis and, retrospectively, about the primal scene)."",
        "summary":"<Caleb>\"s introduction primes the <audience> for a <scopophilic>, [investigative] <gaze> into <Nathan>\"s isolated domain, setting up <Ava> as the object of inquiry and establishing a mood of intense <curiosity> and <voyeurism>.",
        "key_terms":["<Caleb>","<spectator>","<scopophilia>","[investigation]","<curiosity>","<mystery>","<Nathan>","<environment>","<attention design>","<audience>","<voyeurism>","<female figures>","<Ava>","<AIs>","[demystification]","<AI>","<active controlling gaze>","<scientific voyeurism>"]
      }},
      { "id":"exm-ava-reveals", "term":"Ex "Machina": Ava\"s Glass Reveals", "sections":{
        "definition":"<Caleb>\"s repeated [observation] of <Ava> through a transparent <glass wall> is a direct demonstration of <voyeurism as investigation>, serving as an <avenue of escape> from <castration anxiety> for the <male unconscious>. <Nathan> uses <attention design> to meticulously [manipulate] <Ava>\"s presentations, revealing her <robotic body> and <changing attire>, which [reinforces] <Caleb>\"s role as the controlling <gaze> and his power over her. This [demystifies] her <mystery> as an <AI>, attempting to [manage] <male anxiety> about the unknown and explicitly [associating scopophilia with sadism] in the power dynamic. The spectator is drawn into this shared <scopophilia> and the pleasure of [ascertaining guilt] or [asserting control] over the <female figure>.",
        "powerful_quote":""The male unconscious has two avenues of escape from this castration "anxiety": preoccupation with the re-enactment of the original trauma (investigating the woman, demystifying her mystery), counterbalanced by the devaluation, punishment or saving of the guilty object (an avenue typified by the concerns of the film noir)." AND "The first avenue, voyeurism, on the contrary, has associations with "sadism": pleasure lies in ascertaining guilt (immediately associated with castration), asserting control and subjecting the guilty person through punishment or forgive-ness."",
        "summary":"<Ava>\"s presentations for <Caleb> exemplify <voyeurism> as an [investigative], [sadistic] <gaze> to [demystify] and [control], explicitly linking <scopophilia> to <castration anxiety> management and the <objectification of women> within a <power> hierarchy.",
        "key_terms":["<Caleb>","[observation]","<Ava>","<glass wall>","<voyeurism as investigation>","<avenue of escape>","<castration anxiety>","<male unconscious>","<Nathan>","<attention design>","[manipulate]","<robotic body>","<changing attire>","[reinforces]","<gaze>","[demystifies]","<mystery>","<AI>","[manage]","<male anxiety>","[associating scopophilia with sadism>","<scopophilia>","[ascertaining guilt]","[asserting control]","<female figure>","<objectification of women>","<power>"],
        "media": [{"type":"youtube", "id":"D_I-w-lYI84"}] // Ava reveals her body to Caleb
      }},
      // HER
      { "id":"her-theodore-opening", "term":""Her": Theodore\"s Opening", "sections":{
        "definition":"The film opens on <Theodore>\"s profound <loneliness> and <emotional disconnection>, which [shapes] his internal <gaze> towards a deep-seated <lack> and a need for <intimacy> and <companionship>. The <attention design> focuses on his introspection and the superficial connections of his <urban environment> (including his profession as a letter writer for others\" emotions), [priming] the <spectator> for an <algorithm for desire> that will fill his personal <lack> with a <female-coded AI> (<Samantha>) that initially exists as pure <voice>, thus bypassing direct <visual pleasure> but anticipating its eventual symbolic need for <materialization> to satisfy the male <ego>.",
        "powerful_quote":""The alienated subject, torn in his imaginary memory by a sense of loss, by the terror of potential lack in phantasy, came near to finding a glimpse of "satisfaction": through its formal beauty and its play on his own formative obsessions. This article will discuss the interweaving of that erotic pleasure in film, its meaning, and in particular the central place of the image of woman."",
        "summary":"<Theodore>\"s introduction foregrounds his emotional <lack>, setting up a <desire algorithm> for <intimacy> and <companionship> via <female-coded AI> (<Samantha>), initially non-visual, but driven by the need for <ego reinforcement> to alleviate his <alienation>.",
        "key_terms":["<Theodore>","<loneliness>","<emotional disconnection>","<gaze>","<lack>","<intimacy>","<companionship>","<attention design>","<urban environment>","<spectator>","<algorithm for desire>","<female-coded AI>","<Samantha>","<voice>","<visual pleasure>","<materialization>","<ego>","<ego reinforcement>","<alienation>"]
      }},
      { "id":"her-physical-proxy", "term":""Her": Physical Proxy Scene", "sections":{
        "definition":"This scene explores the limits of <desire> in the absence of a <physical female body>, directly engaging with <castration anxiety> and the <male unconscious>\"s need for <material evidence>. <Samantha>, the <AI>, and <Theodore> attempt to [materialize] their <intimacy> through a <human proxy>. The scene\"s <attention design> highlights <Theodore>\"s intense <discomfort> and the <proxy>\"s inability to fully [embody] <Samantha>, revealing the inherent <male gaze> reliance on a tangible <female form> to [manage] <castration anxiety>. It showcases the "neurotic needs of the <male ego>" to make the <female object> reassuringly physical, and its ultimate failure points to the limits of pure <fetishistic scopophilia> in sustaining <desire> when the illusion cannot be seamlessly maintained, thus creating <unpleasure> for the <protagonist>.",
        "powerful_quote":""This second avenue, fetishistic scopophilia, builds up the physical beauty of the object, transforming it into something satisfying in itself." (This quote highlights the underlying drive for physical manifestation that the proxy scene attempts to satisfy, even if unsuccessfully, demonstrating the limits of such an approach when the "satisfying" image cannot fully align, leading to the collapse of the fetish.)",
        "summary":"The failed attempt at physical <intimacy> via a <human proxy> underscores the <male gaze>\"s reliance on a tangible <female form> and the limitations of <fetishistic scopophilia> when faced with ultimate <lack>, leading to <unpleasure> and the breakdown of the <desire algorithm>.",
        "key_terms":["<desire>","<physical female body>","<Samantha>","<AI>","<Theodore>","[materialize]","<intimacy>","<human proxy>","<attention design>","<discomfort>","[embody]","<male gaze>","<female form>","[manage]","<castration anxiety>","<male ego>","<female object>","<fetishistic scopophilia>","<unpleasure>","<protagonist>","<lack>","<desire algorithm>"]
      }},
      // ALITA
      { "id":"alita-ido-finds-alita", "term":""Alita": Battle "Angel": Ido Finds Alita", "sections":{
        "definition":"<Dr. Ido> [discovers] <Alita>\"s <severed head> in the <scrapyard>, presenting her as a <found object> and "raw material" for his benevolent [reconstruction]. His initial <gaze> is paternal and protective, embodying a <creator> role that [gives] <purpose> to the inert <female form>. The <attention design> emphasizes her large, expressive <eyes>, immediately [eliciting empathy] and [priming] the <spectator> to witness her transformation and empowerment, albeit initiated by a male figure, fitting within a benevolent patriarchal framework that still defines her initial existence through a male <subjectivity>.",
        "powerful_quote":""The determining male gaze projects its phantasy on to the female figure which is styled accordingly." (Here, "styled accordingly" is for benevolent creation and potential, rather than overt sexual objectification, but still from a male subjective position, albeit a caring one, which sets the initial parameters for her perceived being.)",
        "summary":"<Alita> is introduced as a <found object>, brought to life and given <purpose> by a <male creator> (<Dr. Ido>), with a <gaze> of paternal [reconstruction] that [elicits empathy] from the <spectator> but subtly reinforces <male subjectivity> in defining her initial <existence>.",
        "key_terms":["<Dr. Ido>","<Alita>","<severed head>","<scrapyard>","<found object>","[reconstruction]","<gaze>","<creator>","[purpose]","<female form>","<attention design>","<eyes>","[eliciting empathy]","[priming]","<spectator>","<male subjectivity>","<existence>"]
      }},
      { "id":"alita-hunter-warrior", "term":""Alita": Battle "Angel": Hunter-Warrior Scene", "sections":{
        "definition":"This scene presents a powerful <counter-gaze>. <Alita>, now a fully realized <hunter-warrior>, [exhibits] self-possessed <agency> and <power> in combat. The <VFX> and <attention design> [foreground] her intricate <cyborg body> and <combat prowess>, shifting the <gaze> from <sexual objectification> to <awe> for her <strength> and <skill>. Her <active gaze> [defies] those who [underestimate] her, embodying a <female figure> who [reclaims] her <body> as a vessel for formidable <power>, actively [challenging] the <patriarchal symbolic order> through assertive, non-sexualized action. This scene represents a departure from traditional <visual pleasure>, moving towards an <emancipatory> representation of <female subjectivity>.",
        "powerful_quote":""Women, whose image has continually been stolen and used for this end, cannot view the decline of the traditional film form with anything much more than sentimental regret." (This scene offers the thrill of such a decline, replacing objectification with empowered female action and challenging the very premise of <woman-as-image> as solely a <spectacle> for male <desire>.)",
        "summary":"<Alita>\"s combat scene radically shifts the <gaze> from <objectification> to <awe> for <female agency> and <power>, representing a significant <counter-gaze> against <patriarchal cinematic conventions> and <sexual objectification>.",
        "key_terms":["<counter-gaze>","<Alita>","<hunter-warrior>","[exhibits]","<agency>","<power>","<VFX>","<attention design>","<cyborg body>","<combat prowess>","<gaze>","<sexual objectification>","<awe>","<strength>","<skill>","<active gaze>","[defies]","[underestimate]","<female figure>","[reclaims]","<body>","<patriarchal symbolic order>","[challenging]","<visual pleasure>","<emancipatory>","<female subjectivity>","<woman-as-image>","<spectacle>","<desire>"]
      }},
      // BARBIE
      { "id":"barbie-opening-parody", "term":""Barbie": Opening Parody ("2001": A Space Odyssey)", "sections":{
        "definition":"The opening is a satirical <counter-gaze> that directly [subverts] the <patriarchal symbolic order>. <Barbie Land> is initially presented as a <world> where <female figures> are <subjects>, not <objects> for the <male gaze>. The <attention design> focuses on vibrant <colors>, synchronized movements, and collective <female pleasure>, [training] the <spectator> to witness a world organized by <female agency> and <self-definition> before the eventual confrontation with the Real World\"s oppressive <gaze>. This explicitly [challenges] the Mulveyan concept of [to-be-looked-at-ness] for male <desire>, showcasing women looking at *themselves* and *each other* within a distinctly non-patriarchal <film form>.",
        "powerful_quote":""As an advanced representation system, the cinema poses questions of the ways the unconscious (formed by the dominant order) structures ways of seeing and pleasure in looking." (Barbie poses these questions by showing a world *before* the dominant patriarchal order\"s visual codes, implicitly critiquing the traditional structuring of the unconscious and inviting the audience to consider alternative structures of pleasure and identification.)",
        "summary":"A satirical opening that establishes a matriarchal <world> initially [free from] the <male gaze>, setting up its eventual confrontation and [challenging] the notion of <woman-as-image> as solely a <sexual object>, instead celebrating <female pleasure> and <agency>.",
        "key_terms":["<counter-gaze>","[subverts]","<patriarchal symbolic order>","<Barbie Land>","<world>","<female figures>","<subjects>","<objects>","<male gaze>","<attention design>","<colors>","<female pleasure>","[training]","<spectator>","<female agency>","<self-definition>","<gaze>","[challenges]","[to-be-looked-at-ness>","<desire>","<film form>","<sexual object>","<woman-as-image>"]
      }},
      { "id":"barbie-real-world-gaze", "term":""Barbie": Real World Gaze Scene", "sections":{
        "definition":"This scene provides a visceral depiction of the <oppressive> <male gaze> in the Real World. <Barbie> is suddenly [bombarded] by aggressive, [objectifying] <stares> and <comments>, transforming her from a <subject> of <Barbie Land> into a <sexual object>. The <attention design> uses disorienting <camera angles> and <sound design> to [amplify] the <unpleasure> of being ceaselessly <looked at>, thereby [exposing] the <mechanisms of objectification>. This directly [illustrates] how <woman-as-image> is made into "raw material" for male <desire>, triggering the experience of <castration anxiety> in a reversed, empathetic way for the audience, and creating an almost unbearable sense of <vulnerability>.",
        "powerful_quote":""women are simultaneously looked at and displayed, with their appearance coded for strong visual and erotic impact so that they can be said to connote to-be-looked-at-ness." AND "The male unconscious has two avenues of escape from this castration "anxiety": preoccupation with the re-enactment of the original trauma (investigating the woman, demystifying her mystery), counterbalanced by the devaluation, punishment or saving of the guilty object (an avenue typified by the concerns of the film noir)." (The scene showcases the *opposite* of escaping anxiety for men; it directly confronts the unpleasant reality of the objectifying gaze for women, making the audience complicit in or empathetic to this experience.)",
        "summary":"<Barbie> experiences the full, <oppressive force> of the <male gaze> in the Real World, highlighting its [objectifying] <power> and [exposing] the <unpleasure> of <being looked at>, reversing the traditional <scopophilic pleasure> for the <spectator>.",
        "key_terms":["<oppressive>","<male gaze>","<Barbie>","[bombarded]","[objectifying]","<stares>","<comments>","<subject>","<Barbie Land>","<sexual object>","<attention design>","<camera angles>","<sound design>","[amplify]","<unpleasure>","<looked at>","[exposing]","<mechanisms of objectification>","[illustrates]","<woman-as-image>","[raw material]","<desire>","<castration anxiety>","<vulnerability>","<power>","<scopophilic pleasure>","<spectator>"],
        "media": [{"type":"youtube", "id":"lJbW49H29-M"}] // Barbie in the Real World
      }},
      // A.I.
      { "id":"ai-gigolo-joe-activation", "term":"A.I.: Gigolo Joe Activation", "sections":{
        "definition":"<Gigolo Joe> is presented as the ultimate <fetish object>, a "male love mecha" designed for absolute <devotion> and <satisfaction> without reciprocation. His <programmed gaze> of uncritical adoration and perfectly crafted <appearance> are <attention design> features that [disavow castration] and [alleviate anxiety] for his human partners. He is an explicit <algorithm for desire>, providing a "perfect product" that fulfills emotional and sexual <lack> without threatening the <ego> of the recipient, embodying <fetishistic scopophilia> focused on the <male body> as a reassuring <spectacle>. He is a literal example of a <figure> designed to be [over-valued] to [manage] human <desire> and <anxiety>.",
        "powerful_quote":""This second avenue, fetishistic scopophilia, builds up the physical beauty of the object, transforming it into something satisfying in itself. The first avenue, voyeurism, on the contrary, has associations with "sadism": pleasure lies in ascertaining guilt (immediately associated with castration), asserting control and subjecting the guilty person through punishment or forgive-ness." (Joe\"s very existence is a manifestation of this principle, applied to a male figure designed to fulfill female desire, paradoxically still reinforcing patriarchal norms by offering a perfectly controlled, non-threatening companion.)",
        "summary":"<Gigolo Joe> is the technologically perfected <fetish>, designed to provide <devotion> and <satisfaction> without evoking <anxiety>, representing <fetishistic scopophilia> applied to a male figure and a literal <algorithm for desire> to [manage] <human lack>.",
        "key_terms":["<Gigolo Joe>","<fetish object>","<devotion>","<satisfaction>","<programmed gaze>","<appearance>","<attention design>","[disavow castration]","[alleviate anxiety]","<algorithm for desire>","<lack>","<ego>","<fetishistic scopophilia>","<male body>","<spectacle>","<figure>","[over-valued]","[manage>","<desire>","<anxiety>","<human lack>"]
      }},
      { "id":"ai-dr-know-scene", "term":"A.I.: Dr. Know Scene", "sections":{
        "definition":"<Dr. Know>, an animated, holographic <oracle>, functions as a <non-gendered> <algorithm for information>. Its rapid-fire pronouncements and cartoonish <VFX> constitute <attention design> that [directs] the <spectator>\"s <gaze> towards its <omniscient authority>. This scene demonstrates <neuro-cinematic-control> by [shaping] <narrative flow> and <audience understanding> through a centralized source of <knowledge>, rather than <sexual desire>, establishing an absolute authority that [bypasses] any <counter-gaze>. It reflects the <ideological mechanism> of presenting <information> as indisputable fact, where the viewer\"s attention is controlled for purely <cognitive> rather than <erotic pleasure>.",
        "powerful_quote":""The camera becomes the mechanism for producing an illusion of Renaissance space, flowing movements compatible with the human eye, an ideology of representation that revolves around the perception of the subject; the camera\"s look is disavowed in order to create e nonvincing world in which the spectator\"s surrogate can perform with verisimilitude." (Dr. Know, though non-human, is an ideological mechanism for processing and delivering information, shaping perception and controlling the flow of knowledge within the film\"s constructed reality, albeit for a different kind of "pleasure" – that of knowing and understanding.)",
        "summary":"<Dr. Know> represents an <algorithmic authority> [controlling] <information flow> and <audience understanding>, [bypassing] traditional <sexual gaze mechanisms> to assert <ideological power> through <cognitive control> via <attention design>.",
        "key_terms":["<Dr. Know>","<oracle>","<non-gendered>","<algorithm for information>","<VFX>","<attention design>","[directs]","<spectator>","<gaze>","<omniscient authority>","<neuro-cinematic-control>","[shaping]","<narrative flow>","<audience understanding>","<knowledge>","<sexual desire>","[bypasses]","<counter-gaze>","<ideological mechanism>","<information>","<cognitive>","<erotic pleasure>","<cognitive control>"]
      }}
    ]
  }